backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
media_folder: "/images/" # Media files will be stored in the repo under images/

collections:
  - name: "technology"
    label: "Technology"
    folder: "_technology"
    create: true
    fields:
      - {label: "Title", name: "title"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}